spring:
  application:
    name: account-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/financial
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

server:
  port: 8081

eureka:
  client:
    service-url:
      default-zone: http://admin:admin@localhost:8761/eureka
