spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:4200"
            allow-credentials: true
            allowed-headers: "*"
            allowed-methods: "*"
            exposed-headers: "*"

server:
  port: 8080

eureka:
  client:
    service-url:
      default-zone: http://admin:admin@localhost:8761/eureka